collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3225806
  brandStrength: 1
  lightness: 0.09139785
  brandColors:
    - '#FFFFFF'
    - '#4D1B1A'
    - '#E8CF73'
    - '#C09143'
    - '#8D6A68'
  rhythmicContrast: 0.9587814
typography_spectrum: 0.172043
layout_spectrum: 0.9784946
name: '83'
