collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9336917
  brandStrength: 0.7329749
  lightness: 0.8028674
  brandColors:
    - '#FFFFFF'
    - '#4D1B1A'
    - '#E8CF73'
    - '#C09143'
    - '#8D6A68'
  rhythmicContrast: 0.5197133
typography_spectrum: 0.04659498
layout_spectrum: 0.9193549
name: '83'
